"use client";

import { FormEvent, useMemo, useState } from "react";
import { minutesBetween } from "@/lib/date";
import type { AvailabilityWindow, PlannerData } from "@/lib/types";
import { Icon } from "@/components/ui/icon";

const weekday = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];

export function AnalyticsView({ data }: { data: PlannerData }) {
  const stats = useMemo(() => {
    const completed = data.sessions.filter((session) => session.status === "COMPLETED");
    const planned = data.sessions.filter((session) => session.status === "PLANNED");
    const actualMins = completed.reduce((sum, session) => sum + (session.actualMins ?? minutesBetween(session.startsAt, session.endsAt)), 0);
    const plannedMins = data.sessions.reduce((sum, session) => sum + minutesBetween(session.startsAt, session.endsAt), 0);
    const taskCompletion = Math.round(data.tasks.reduce((sum, task) => sum + task.progress, 0) / Math.max(1, data.tasks.length));
    return { completed: completed.length, planned: planned.length, actualMins, plannedMins, taskCompletion };
  }, [data]);
  const max = Math.max(2, ...data.courses.map((course) => data.sessions.filter((session) => session.courseId === course.id).reduce((sum, session) => sum + minutesBetween(session.startsAt, session.endsAt) / 60, 0)));
  return <div className="view"><div className="view-heading"><div><div className="eyebrow">REFLECTION</div><h1>Study analytics</h1><p>See where your time is going, then adjust with confidence.</p></div><button className="soft-button"><Icon name="calendar" size={16} /> This week</button></div>
    <section className="analytics-stats"><Stat icon="clock" label="Focused hours" value={`${(stats.actualMins / 60).toFixed(1)}h`} detail={`${(stats.plannedMins / 60).toFixed(1)}h planned`} color="violet" /><Stat icon="check" label="Sessions completed" value={String(stats.completed)} detail={`${stats.planned} upcoming sessions`} color="green" /><Stat icon="target" label="Task completion" value={`${stats.taskCompletion}%`} detail="Across all active courses" color="orange" /><Stat icon="lightning" label="On-time pace" value="92%" detail="Up 4% this month" color="blue" /></section>
    <div className="analytics-grid"><section className="panel course-time-panel"><div className="panel-heading"><div><h2>Time by course</h2><p>Planned and completed sessions</p></div><button className="small-icon"><Icon name="more" size={18} /></button></div><div className="horizontal-bars">{data.courses.map((course) => { const amount = data.sessions.filter((session) => session.courseId === course.id).reduce((sum, session) => sum + minutesBetween(session.startsAt, session.endsAt) / 60, 0); return <div key={course.id}><div><span className="course-dot" style={{ background: course.color }} /><strong>{course.code}</strong><em>{amount.toFixed(1)}h</em></div><div className="horizontal-track"><i style={{ width: `${amount / max * 100}%`, background: course.color }} /></div></div>; })}</div></section><section className="panel consistency-panel"><div className="panel-heading"><div><h2>Consistency</h2><p>Small sessions add up</p></div></div><div className="consistency-number"><strong>3</strong><span>day current streak</span></div><div className="heat-row">{Array.from({ length: 14 }, (_, i) => <i key={i} className={i > 4 && i < 10 ? `heat h${(i % 3) + 1}` : "heat"} />)}</div><p className="subtle-note">Schedule one more focused block tomorrow to keep your streak going.</p></section></div>
    <section className="panel session-quality"><div className="panel-heading"><div><h2>Session quality</h2><p>Learn when you work best</p></div></div><div className="quality-grid"><div><span>Best focus window</span><strong>4:00–6:00 PM</strong><p>Your completed sessions are longest and most consistent here.</p></div><div><span>Average session</span><strong>{stats.completed ? `${Math.round(stats.actualMins / stats.completed)} min` : "—"}</strong><p>Sweet spot: 60–90 minute blocks with a short reset.</p></div><div><span>Next insight</span><strong>Protect Tuesday</strong><p>A high-leverage 2-hour opening is still available for your math exam.</p></div></div></section>
  </div>;
}

function Stat({ icon, label, value, detail, color }: { icon: "clock" | "check" | "target" | "lightning"; label: string; value: string; detail: string; color: string }) { return <article className={`analytic-stat ${color}`}><span><Icon name={icon} size={18} /></span><div><p>{label}</p><strong>{value}</strong><small>{detail}</small></div></article>; }

export function AssistantView({ data, mode, initialQuestion, onQuestionUsed }: { data: PlannerData; mode: "authenticated" | "demo"; initialQuestion?: string; onQuestionUsed: () => void }) {
  const [question, setQuestion] = useState(initialQuestion ?? "");
  const [messages, setMessages] = useState<Array<{ role: "assistant" | "user"; text: string }>>([{ role: "assistant", text: "I’ve looked at your plan. Ask me what to work on, where you’re at risk, or how to prepare for an exam." }]);
  const [loading, setLoading] = useState(false);
  const submit = async (event?: FormEvent) => { event?.preventDefault(); const trimmed = question.trim(); if (!trimmed || loading) return; setMessages((current) => [...current, { role: "user", text: trimmed }]); setQuestion(""); setLoading(true); try { const payload = mode === "demo" ? { question: trimmed, demo: true, data } : { question: trimmed }; const response = await fetch("/api/assistant", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const body = await response.json() as { answer?: string; error?: string; notice?: string }; const text = body.answer ? [body.answer, body.notice].filter(Boolean).join(" ") : body.error ?? "I couldn’t process that just now. Try again in a moment."; setMessages((current) => [...current, { role: "assistant", text }]); } catch { setMessages((current) => [...current, { role: "assistant", text: "I’m offline right now, but your schedule is still available in the calendar." }]); } finally { setLoading(false); onQuestionUsed(); } };
  return <div className="view assistant-view"><div className="assistant-hero"><div className="assistant-logo large"><Icon name="sparkle" size={23} /></div><div><div className="eyebrow">PERSONAL STUDY COACH</div><h1>Let’s make your week feel lighter.</h1><p>StudyPilot uses your deadlines, workload, and planned sessions to give focused advice.</p></div></div><div className="assistant-chat" aria-live="polite"><div className="chat-messages">{messages.map((message, index) => <article className={`chat-message ${message.role}`} key={index}>{message.role === "assistant" && <span className="chat-avatar"><Icon name="sparkle" size={14} /></span>}<p>{message.text}</p></article>)}{loading && <article className="chat-message assistant"><span className="chat-avatar"><Icon name="sparkle" size={14} /></span><p className="typing"><i /><i /><i /></p></article>}</div><div className="suggestion-chips">{["What should I study tonight?", "Am I behind on anything?", "How should I prepare for my math exam?"].map((prompt) => <button key={prompt} onClick={() => setQuestion(prompt)}>{prompt}</button>)}</div><form className="chat-input" onSubmit={submit}><input value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="Ask about your study plan…" aria-label="Ask the AI study assistant" /><button type="submit" disabled={!question.trim() || loading} aria-label="Send question"><Icon name="send" size={18} /></button></form><p className="privacy-note">Only your course and task context is used to tailor this answer.</p></div></div>;
}

export function SettingsView({ data, onAvailabilityChange }: { data: PlannerData; onAvailabilityChange: (availability: AvailabilityWindow[]) => void }) {
  const [saved, setSaved] = useState(false);
  const toTime = (mins: number) => `${String(Math.floor(mins / 60)).padStart(2, "0")}:${String(mins % 60).padStart(2, "0")}`;
  const save = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const availability = weekday.flatMap((_, dayOfWeek) => { const enabled = form.get(`enabled-${dayOfWeek}`) === "on"; const start = String(form.get(`start-${dayOfWeek}`)); const end = String(form.get(`end-${dayOfWeek}`)); const mins = (time: string) => { const [hour, minute] = time.split(":").map(Number); return hour * 60 + minute; }; return enabled && mins(end) > mins(start) ? [{ dayOfWeek, startMins: mins(start), endMins: mins(end) }] : []; }); onAvailabilityChange(availability); setSaved(true); window.setTimeout(() => setSaved(false), 2200); };
  return <div className="view settings-view"><div className="view-heading"><div><div className="eyebrow">PREFERENCES</div><h1>Study settings</h1><p>Availability gives the planner a realistic frame for every recommendation.</p></div></div><form className="settings-grid" onSubmit={save}><section className="panel availability-panel"><div className="panel-heading"><div><h2>Weekly availability</h2><p>When can you reliably study?</p></div></div><div className="availability-list">{weekday.map((label, day) => { const window = data.availability.find((item) => item.dayOfWeek === day); return <div className="availability-row" key={label}><label className="toggle"><input name={`enabled-${day}`} type="checkbox" defaultChecked={Boolean(window)} /><span /></label><strong>{label}</strong><input name={`start-${day}`} type="time" defaultValue={toTime(window?.startMins ?? 1020)} /><span>to</span><input name={`end-${day}`} type="time" defaultValue={toTime(window?.endMins ?? 1200)} /></div>; })}</div><div className="form-actions"><span className="saved-message">{saved ? "Availability saved" : ""}</span><button className="primary-button" type="submit">Save availability</button></div></section><section className="panel planning-preferences"><div className="panel-heading"><div><h2>Planning preferences</h2><p>Defaults your planner will honor</p></div></div><div className="preference-list"><Preference label="Maximum focus block" value="90 minutes" /><Preference label="Recovery break" value="15 minutes" /><Preference label="Planning horizon" value="Next 14 days" /><Preference label="Schedule weekends" value="Yes, if available" /></div><div className="blocked-info"><Icon name="calendar" size={17} /><span><strong>Specific blocked time</strong> is supported in the data model and will be excluded from every plan.</span></div></section></form></div>;
}

function Preference({ label, value }: { label: string; value: string }) { return <div><span>{label}</span><button type="button">{value} <Icon name="chevron" size={15} /></button></div>; }
