import Link from "next/link";
import { Icon } from "@/components/ui/icon";

export function LandingPage() {
  return <main className="landing-page">
    <nav className="landing-nav"><Link className="brand" href="/"><span className="brand-mark"><Icon name="lightning" size={19} /></span><span>StudyPilot</span></Link><div><Link className="landing-sign-in" href="/sign-in">Sign in</Link><Link className="primary-button" href="/sign-up">Create account <Icon name="arrow" size={16} /></Link></div></nav>
    <section className="landing-hero"><div className="landing-copy"><div className="landing-pill"><Icon name="sparkle" size={14} /> AI-powered planning for real student life</div><h1>Less planning. <em>More progress.</em></h1><p>StudyPilot turns your deadlines, workload, and real availability into a study plan you can actually follow.</p><div className="landing-actions"><Link className="primary-button landing-primary" href="/sign-up">Create your free account <Icon name="arrow" size={17} /></Link><Link className="soft-button landing-demo" href="/demo"><Icon name="sparkle" size={16} /> Try the demo</Link></div><p className="landing-note">No credit card. Your study data stays private to your account.</p></div>
      <div className="landing-preview" aria-label="Study plan preview"><div className="preview-top"><div><span>GOOD AFTERNOON</span><strong>Your week, in focus.</strong></div><i><Icon name="bell" size={16} /></i></div><div className="preview-focus"><span><Icon name="target" size={17} /></span><div><small>TODAY’S FOCUS</small><strong>Practice diagonalization</strong><p>MATH 208 · 90 min focused block</p></div></div><div className="preview-calendar"><div><span>MON</span><strong>14</strong><i /></div><div className="selected"><span>TUE</span><strong>15</strong><i /><b>3 sessions</b></div><div><span>WED</span><strong>16</strong><i /></div><div><span>THU</span><strong>17</strong><i /></div></div><div className="preview-sessions"><article><span className="preview-dot violet" /><div><strong>Build repository add command</strong><small>CSE 123 · 4:00 PM</small></div><Icon name="check" size={15} /></article><article><span className="preview-dot green" /><div><strong>Practice diagonalization</strong><small>MATH 208 · 6:00 PM</small></div><Icon name="check" size={15} /></article></div></div>
    </section>
    <section className="landing-benefits"><article><span><Icon name="target" size={18} /></span><div><strong>Prioritize what matters</strong><p>Balance deadlines, difficulty, remaining effort, and course goals.</p></div></article><article><span><Icon name="calendar" size={18} /></span><div><strong>Plan around your life</strong><p>Every session respects the availability you set.</p></div></article><article><span><Icon name="sparkle" size={18} /></span><div><strong>Stay a step ahead</strong><p>Ask your AI study coach where to focus next.</p></div></article></section>
  </main>;
}
