"use client";

import { FormEvent, useState } from "react";
import { formatShortDate } from "@/lib/date";
import type { Course, PlannerData, StudyTask, TaskType } from "@/lib/types";
import { Icon } from "@/components/ui/icon";

const taskTypes: TaskType[] = ["ASSIGNMENT", "QUIZ", "EXAM", "PROJECT", "READING", "OTHER"];
const colors = ["#7567F8", "#20A36B", "#F39A3F", "#E45B78", "#2097C8"];
const blankCourse: Omit<Course, "id"> = { code: "", name: "", professor: "", color: colors[0], icon: "book", priority: 3, targetGrade: 90 };

export function CoursesView({ data, onUpsert, onDelete }: { data: PlannerData; onUpsert: (course: Course) => void; onDelete: (id: string) => void }) {
  const [editing, setEditing] = useState<Course | null>(null);
  const save = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); onUpsert({ id: editing?.id ?? `course-${Date.now()}`, code: String(form.get("code")).toUpperCase(), name: String(form.get("name")), professor: String(form.get("professor")) || undefined, color: String(form.get("color")), icon: "book", priority: Number(form.get("priority")), targetGrade: Number(form.get("targetGrade")) || undefined, currentGrade: editing?.currentGrade }); setEditing(null); };
  return <div className="view"><div className="view-heading"><div><div className="eyebrow">ACADEMICS</div><h1>Your courses</h1><p>Keep priorities, grade goals, and course context in one place.</p></div><button className="primary-button" onClick={() => setEditing({ id: "", ...blankCourse })}><Icon name="plus" size={17} /> Add course</button></div>
    <div className="course-cards">{data.courses.map((course) => { const related = data.tasks.filter((task) => task.courseId === course.id); const progress = Math.round(related.reduce((sum, task) => sum + task.progress, 0) / Math.max(1, related.length)); return <article className="course-card" key={course.id}><div className="course-card-head"><div className="large-course-symbol" style={{ color: course.color, background: `${course.color}18` }}><Icon name={course.icon} size={25} /></div><div className="course-actions"><button className="small-icon" onClick={() => setEditing(course)} aria-label={`Edit ${course.code}`}><Icon name="edit" size={15} /></button><button className="small-icon" onClick={() => onDelete(course.id)} aria-label={`Delete ${course.code}`}><Icon name="trash" size={15} /></button></div></div><div><span className="course-code" style={{ color: course.color }}>{course.code}</span><h2>{course.name}</h2><p>{course.professor || "Professor not added"}</p></div><div className="course-grade"><div><span>Current grade</span><strong>{course.currentGrade ? `${course.currentGrade}%` : "—"}</strong></div><div><span>Target</span><strong>{course.targetGrade ? `${course.targetGrade}%` : "—"}</strong></div><div><span>Priority</span><strong>{"●".repeat(course.priority)}<i>{"●".repeat(5 - course.priority)}</i></strong></div></div><div className="course-card-progress"><div><span>Coursework progress</span><strong>{progress}%</strong></div><div className="progress-track"><i style={{ width: `${progress}%`, background: course.color }} /></div></div><div className="course-card-footer"><span>{related.filter((task) => task.progress < 100).length} active tasks</span><button onClick={() => setEditing(course)}>Manage <Icon name="arrow" size={14} /></button></div></article>; })}</div>
    {editing && <Modal title={editing.id ? `Edit ${editing.code}` : "Add a course"} onClose={() => setEditing(null)}><form className="form-grid" onSubmit={save}><label>Course name<input name="name" required defaultValue={editing.name} placeholder="Data Structures" /></label><label>Course code<input name="code" required defaultValue={editing.code} placeholder="CSE 123" /></label><label>Professor <input name="professor" defaultValue={editing.professor} placeholder="Optional" /></label><label>Course priority<select name="priority" defaultValue={editing.priority}>{[1,2,3,4,5].map((number) => <option value={number} key={number}>{number} — {number >= 4 ? "High" : number === 3 ? "Medium" : "Low"}</option>)}</select></label><label>Target grade<input name="targetGrade" type="number" min="0" max="100" defaultValue={editing.targetGrade} /></label><fieldset className="color-field"><legend>Course color</legend><div>{colors.map((color) => <label className="color-choice" key={color} style={{ background: color }}><input type="radio" name="color" value={color} defaultChecked={editing.color === color} /><span /></label>)}</div></fieldset><div className="form-actions"><button type="button" className="soft-button" onClick={() => setEditing(null)}>Cancel</button><button className="primary-button" type="submit">Save course</button></div></form></Modal>}
  </div>;
}

export function TasksView({ data, onUpsert, onComplete, onDelete }: { data: PlannerData; onUpsert: (task: StudyTask) => void; onComplete: (id: string) => void; onDelete: (id: string) => void }) {
  const [editing, setEditing] = useState<StudyTask | null>(null);
  const [filter, setFilter] = useState<"ALL" | TaskType>("ALL");
  const tasks = data.tasks.filter((task) => filter === "ALL" || task.type === filter).sort((a, b) => a.dueAt.localeCompare(b.dueAt));
  const save = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const due = new Date(String(form.get("dueAt"))); onUpsert({ id: editing?.id ?? `task-${Date.now()}`, courseId: String(form.get("courseId")), title: String(form.get("title")), type: String(form.get("type")) as TaskType, dueAt: due.toISOString(), estimatedMins: Number(form.get("estimatedHours")) * 60, difficulty: Number(form.get("difficulty")), progress: Number(form.get("progress")), priority: Number(form.get("priority")), notes: String(form.get("notes")) || undefined, completedAt: Number(form.get("progress")) === 100 ? new Date().toISOString() : undefined }); setEditing(null); };
  return <div className="view"><div className="view-heading"><div><div className="eyebrow">WORK QUEUE</div><h1>Tasks & deadlines</h1><p>Break down every deliverable and keep your plan grounded in reality.</p></div><button className="primary-button" onClick={() => setEditing({ id: "", courseId: data.courses[0]?.id ?? "", title: "", type: "ASSIGNMENT", dueAt: new Date().toISOString(), estimatedMins: 120, difficulty: 3, progress: 0, priority: 3 })}><Icon name="plus" size={17} /> Add task</button></div>
    <div className="task-controls"><div className="filter-pills">{(["ALL", ...taskTypes] as const).map((item) => <button key={item} onClick={() => setFilter(item)} className={filter === item ? "selected" : ""}>{item === "ALL" ? "All" : item[0] + item.slice(1).toLowerCase()}</button>)}</div><span>{tasks.filter((task) => task.progress < 100).length} active tasks</span></div>
    <section className="panel task-table"><div className="task-table-head"><span>Task</span><span>Due date</span><span>Progress</span><span>Priority</span><span /></div>{tasks.map((task) => { const course = data.courses.find((item) => item.id === task.courseId); const days = Math.max(0, Math.ceil((new Date(task.dueAt).getTime() - Date.now()) / 86_400_000)); return <article className={`task-table-row ${task.progress === 100 ? "finished" : ""}`} key={task.id}><div className="task-title-cell"><button className={`task-check ${task.progress === 100 ? "checked" : ""}`} aria-label={`Mark ${task.title} complete`} onClick={() => onComplete(task.id)}><Icon name="check" size={13} /></button><div><strong>{task.title}</strong><span style={{ color: course?.color }}>{course?.code} · {task.type.toLowerCase()}</span></div></div><div className="task-due"><strong>{formatShortDate(task.dueAt)}</strong><span className={days <= 2 ? "urgent-text" : ""}>{task.progress === 100 ? "Completed" : days === 0 ? "Due today" : `${days} days left`}</span></div><div className="task-progress"><div className="progress-track"><i style={{ width: `${task.progress}%`, background: course?.color }} /></div><span>{task.progress}%</span></div><span className={`priority-tag p${task.priority}`}>{task.priority >= 4 ? "High" : task.priority === 3 ? "Medium" : "Low"}</span><div className="row-actions"><button className="small-icon" onClick={() => setEditing(task)} aria-label={`Edit ${task.title}`}><Icon name="edit" size={15} /></button><button className="small-icon" onClick={() => onDelete(task.id)} aria-label={`Delete ${task.title}`}><Icon name="trash" size={15} /></button></div></article>; })}</section>
    {editing && <Modal title={editing.id ? "Edit task" : "Add a task"} onClose={() => setEditing(null)}><form className="form-grid" onSubmit={save}><label className="full">Task title<input name="title" required defaultValue={editing.title} placeholder="e.g. Problem set 4" /></label><label>Course<select name="courseId" defaultValue={editing.courseId}>{data.courses.map((course) => <option value={course.id} key={course.id}>{course.code}</option>)}</select></label><label>Type<select name="type" defaultValue={editing.type}>{taskTypes.map((type) => <option value={type} key={type}>{type[0] + type.slice(1).toLowerCase()}</option>)}</select></label><label>Due date<input name="dueAt" type="datetime-local" required defaultValue={editing.dueAt.slice(0, 16)} /></label><label>Estimated hours<input name="estimatedHours" type="number" step="0.5" min="0.25" defaultValue={editing.estimatedMins / 60} /></label><label>Difficulty<select name="difficulty" defaultValue={editing.difficulty}>{[1,2,3,4,5].map((number) => <option value={number} key={number}>{number} / 5</option>)}</select></label><label>Priority<select name="priority" defaultValue={editing.priority}>{[1,2,3,4,5].map((number) => <option value={number} key={number}>{number} / 5</option>)}</select></label><label>Current progress<input name="progress" type="number" min="0" max="100" defaultValue={editing.progress} /></label><label className="full">Notes<textarea name="notes" defaultValue={editing.notes} placeholder="Helpful context for your future self or AI study coach…" /></label><div className="form-actions"><button type="button" className="soft-button" onClick={() => setEditing(null)}>Cancel</button><button className="primary-button" type="submit">Save task</button></div></form></Modal>}
  </div>;
}

export function Modal({ title, children, onClose }: { title: string; children: React.ReactNode; onClose: () => void }) { return <div className="modal-backdrop" role="presentation" onMouseDown={onClose}><section className="form-modal" role="dialog" aria-modal="true" aria-label={title} onMouseDown={(event) => event.stopPropagation()}><div className="modal-title"><h2>{title}</h2><button className="modal-close" onClick={onClose} aria-label="Close"><Icon name="close" size={18} /></button></div>{children}</section></div>; }
